import os
from dotenv import load_dotenv
# File names
products_file = "hookah_products.xlsx"
suppliers_file = "suppliers.xlsx"
employees_file = "hookah_employees.xlsx"
credentials_file = "hookah_credentials.txt"
sales_journal_file = "sales_journal.xlsx"
accounts_receivable_file = "accounts_receivable.xlsx"
accounts_payable_file = "accounts_payable.xlsx"

# Data paths
EXCEL_DATA_PATH = "excel_data"
MONGODB_DATA_PATH = "mongodb_data"

# Collection names
MONGODB_COLLECTIONS = {
    "products": "products",
    "inventory": "inventory",
    "suppliers": "suppliers",
    "sales_journal": "sales_journal",
    "accounts_receivable": "accounts_receivable",
    "accounts_payable": "accounts_payable",
    "employees": "employees",
    "customers": "customers",
    "store_products": "store_products"
}

# Excel file paths
EXCEL_FILES = {
    "products": os.path.join(EXCEL_DATA_PATH, "hookah_products.xlsx"),
    "inventory": os.path.join(EXCEL_DATA_PATH, "hookah_inventory.xlsx"),
    "suppliers": os.path.join(EXCEL_DATA_PATH, "suppliers.xlsx"),
    "sales_journal": os.path.join(EXCEL_DATA_PATH, "sales_journal.xlsx"),
    "accounts_receivable": os.path.join(EXCEL_DATA_PATH, "accounts_receivable.xlsx"),
    "accounts_payable": os.path.join(EXCEL_DATA_PATH, "accounts_payable.xlsx"),
    "employees": os.path.join(EXCEL_DATA_PATH, "hookah_employees.xlsx"),
    "store_products": os.path.join(EXCEL_DATA_PATH, "hookah_store_products.xlsx")
}

# MongoDB configuration
load_dotenv()
MONGODB_URI = os.getenv("MONGODB_URI", "mongodb://localhost:27017/")
MONGODB_DB_NAME = os.getenv("MONGODB_DB_NAME", "hookah_shop_db")

# Hookah types and flavors
HOOKAH_TYPES = ["Traditional", "Modern", "Portable", "Electric"]
HOOKAH_FLAVORS = ["Apple", "Mint", "Grape", "Watermelon", "Orange", "Mixed"]

# Language strings
LANGUAGES = {
    "en": {
        "title": "Hookah Shop Management System",
        "hookah_heaven": "Hookah Heaven",
        "username": "Username",
        "password": "Password",
        "login": "Login",
        "login_failed": "Login failed. Please check your credentials.",
        "manage_products": "Manage Products",
        "manage_inventory": "Manage Inventory",
        "record_sale": "Record Sale",
        "view_bill": "View Bill",
        "view_suppliers": "View Suppliers",
        "view_sales_records": "View Sales Records",
        "exit": "Exit",
        "product_management": "Product Management",
        "add_product": "Add Product",
        "edit_product": "Edit Product",
        "delete_product": "Delete Product",
        "back": "Back",
        "please_fill": "Please fill all required fields",
        "product_added": "Product added successfully",
        "product_updated": "Product updated successfully",
        "product_deleted": "Product deleted successfully",
        "confirm_delete": "Confirm Delete",
        "delete_product": "Are you sure you want to delete this product?",
        "product_not_found": "Product not found",
        "invalid_value": "Invalid value entered",
        "manage_inventory": "Inventory Management",
        "total_products": "Total Products: {}",
        "total_items": "Total Items: {}",
        "total_inventory_value": "Total Value: ${:.2f}",
        "warning_low_stock": "Warning: {} products have low stock!",
        "restock_product": "Restock Product",
        "restock_success": "Successfully restocked {} units of {}",
        "record_sale": "Record Sale",
        "product": "Product",
        "quantity": "Quantity",
        "price_per_unit": "Price per Unit",
        "employee": "Employee",
        "customer_name": "Customer Name",
        "sale_date": "Sale Date",
        "sale_recorded": "Sale recorded: {} units of {} for ${:.2f}",
        "not_enough_stock": "Not enough stock. Only {} available",
        "supplier_management": "Supplier Management",
        "add_supplier": "Add Supplier",
        "edit_supplier": "Edit Supplier",
        "delete_supplier": "Delete Supplier",
        "supplier_added": "Supplier added successfully",
        "supplier_updated": "Supplier updated successfully",
        "supplier_deleted": "Supplier deleted successfully",
        "delete_supplier": "Are you sure you want to delete this supplier?",
        "supplier_not_found": "Supplier not found",
        "bill_section": "Bill Section",
        "print": "Print",
        "restock_date": "Restock Date",
        "record_restock": "Record Restock",
        "supplier": "Supplier",
        "error": "Error",
        "success": "Success",
        "add_worker": "Add Worker",
        "worker_name": "Worker Name",
        "position": "Position",
        "hire_date": "Hire Date",
        "worker_added": "Worker {} added successfully",
        "ai_assistant": "AI Assistant",
        "import_excel": "Import Excel Data",
        "import_success": "Excel data imported successfully",
        "import_fail": "Failed to import Excel data",
        "payment_method": "Payment Method",
        "paid_amount": "Paid Amount",
        "remaining_amount": "Remaining",
        "cash": "Cash",
        "credit": "Credit",
        "partial": "Partial",
        "entry_updated": "Entry updated successfully",
        "fill_all_fields": "Please fill all required fields.",
        "invalid_date_format": "Invalid date format. Please use YYYY-MM-DD",
        "invalid_amount": "Invalid amount. Please enter a number",
        "pay_installment": "Pay Installment",
        "enter_payment": "Enter payment amount",
        "payment_success": "Payment recorded successfully",
        "no_due_bills": "No due bills to pay",
        "pay": "Pay"
    },
    "ar": {
        "title": "نظام إدارة متجر الشيشة",
        "hookah_heaven": "جنة الشيشة",
        "username": "اسم المستخدم",
        "password": "كلمة المرور",
        "login": "تسجيل الدخول",
        "login_failed": "فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد الخاصة بك.",
        "manage_products": "إدارة المنتجات",
        "manage_inventory": "إدارة المخزون",
        "record_sale": "تسجيل بيع",
        "view_bill": "عرض الفاتورة",
        "view_suppliers": "عرض الموردين",
        "view_sales_records": "عرض سجلات المبيعات",
        "exit": "خروج",
        "product_management": "إدارة المنتجات",
        "add_product": "إضافة منتج",
        "edit_product": "تعديل منتج",
        "delete_product": "حذف منتج",
        "back": "رجوع",
        "please_fill": "يرجى ملء جميع الحقول المطلوبة",
        "product_added": "تمت إضافة المنتج بنجاح",
        "product_updated": "تم تحديث المنتج بنجاح",
        "product_deleted": "تم حذف المنتج بنجاح",
        "confirm_delete": "تأكيد الحذف",
        "delete_product": "هل أنت متأكد أنك تريد حذف هذا المنتج؟",
        "product_not_found": "المنتج غير موجود",
        "invalid_value": "قيمة غير صالحة",
        "manage_inventory": "إدارة المخزون",
        "total_products": "إجمالي المنتجات: {}",
        "total_items": "إجمالي العناصر: {}",
        "total_inventory_value": "القيمة الإجمالية: {:.2f} دولار",
        "warning_low_stock": "تحذير: {} منتجات لديها مخزون منخفض!",
        "restock_product": "تجديد المخزون",
        "restock_success": "تم تجديد {} وحدة من {} بنجاح",
        "record_sale": "تسجيل بيع",
        "product": "المنتج",
        "quantity": "الكمية",
        "price_per_unit": "السعر لكل وحدة",
        "employee": "الموظف",
        "customer_name": "اسم العميل",
        "sale_date": "تاريخ البيع",
        "sale_recorded": "تم تسجيل البيع: {} وحدة من {} مقابل {:.2f} دولار",
        "not_enough_stock": "لا يوجد مخزون كافٍ. المتاح فقط {}",
        "supplier_management": "إدارة الموردين",
        "add_supplier": "إضافة مورد",
        "edit_supplier": "تعديل مورد",
        "delete_supplier": "حذف مورد",
        "supplier_added": "تمت إضافة المورد بنجاح",
        "supplier_updated": "تم تحديث المورد بنجاح",
        "supplier_deleted": "تم حذف المورد بنجاح",
        "delete_supplier": "هل أنت متأكد أنك تريد حذف هذا المورد؟",
        "supplier_not_found": "المورد غير موجود",
        "bill_section": "قسم الفاتورة",
        "print": "طباعة",
        "restock_date": "تاريخ التجديد",
        "record_restock": "تسجيل التجديد",
        "supplier": "المورد",
        "error": "خطأ",
        "success": "نجاح",
        "add_worker": "إضافة عامل",
        "worker_name": "اسم العامل",
        "position": "المنصب",
        "hire_date": "تاريخ التوظيف",
        "worker_added": "تمت إضافة العامل {} بنجاح",
        "ai_assistant": "مساعد الذكاء الاصطناعي",
        "import_excel": "استيراد بيانات إكسل",
        "import_success": "تم استيراد بيانات إكسل بنجاح",
        "import_fail": "فشل في استيراد بيانات إكسل",
        "payment_method": "طريقة الدفع / Payment Method",
        "paid_amount": "المبلغ المدفوع / Paid Amount",
        "remaining_amount": "المتبقي / Remaining",
        "cash": "نقدي / Cash",
        "credit": "آجل / Credit",
        "partial": "جزئي / Partial",
        "entry_updated": "تم تحديث السجل بنجاح / Entry updated successfully",
        "fill_all_fields": "يرجى ملء جميع الحقول المطلوبة / Please fill all required fields.",
        "invalid_date_format": "تنسيق التاريخ غير صحيح. استخدم YYYY-MM-DD / Invalid date format. Please use YYYY-MM-DD.",
        "invalid_amount": "قيمة غير صالحة. يرجى إدخال رقم / Invalid amount. Please enter a number.",
        "pay_installment": "تسديد دفعة / Pay Installment",
        "enter_payment": "أدخل مبلغ الدفعة / Enter payment amount",
        "payment_success": "تم تسجيل الدفعة بنجاح / Payment recorded successfully",
        "no_due_bills": "لا توجد فواتير مستحقة للدفع / No due bills to pay",
        "pay": "تسديد / Pay"
    }
}
